#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Loading context data "

#
# Create four Store Entities in various locations across Berlin
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "APPEND",
  "entities": [
  	{
  		"id":"urn:ngsi-ld:Store:001","type":"Store",
  		"address":{"type":"PostalAddress","value":{"streetAddress":"Bornholmer Straße 65","addressRegion":"Berlin","addressLocality":"Prenzlauer Berg","postalCode":"10439"}},
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3986,52.5547]}},
		"name":{"type":"Text","value":"Bosebrucke Einkauf"},
		"url":{"type":"Text","value":"https://www.visitberlin.de/en/mauerpark"},
		"telephone":{"type":"Text","value":"+49 30 1234 0001"},
		"countryCode":{"type":"Text","value":"DE"},
		"capacity":{"type":"Number","value":3200},
		"description":{"type":"Text","value":"Neighborhood supermarket focused on fresh produce and local suppliers."},
		"image":{"type":"Text","value":"https://loremflickr.com/640/480/supermarket"}
  	},
  	{
  		"id":"urn:ngsi-ld:Store:002","type":"Store",
  		"address":{"type":"PostalAddress","value":{"streetAddress":"Friedrichstraße 44","addressRegion":"Berlin","addressLocality":"Kreuzberg","postalCode":"10969"}},
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3903,52.5075]}},
		"name":{"type":"Text","value":"Checkpoint Markt"},
		"url":{"type":"Text","value":"https://www.visitberlin.de/en/checkpoint-charlie"},
		"telephone":{"type":"Text","value":"+49 30 1234 0002"},
		"countryCode":{"type":"Text","value":"DE"},
		"capacity":{"type":"Number","value":4100},
		"description":{"type":"Text","value":"Urban flagship store with broad beverage and ready-to-eat sections."},
		"image":{"type":"Text","value":"https://loremflickr.com/640/480/grocery"}
	},
  	{
  		"id":"urn:ngsi-ld:Store:003","type":"Store",
  		"address":{"type":"PostalAddress","value":{"streetAddress":"Mühlenstrasse 10","addressRegion":"Berlin","addressLocality":"Friedrichshain","postalCode":"10243"}},
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4447,52.5031]}},
		"name":{"type":"Text","value":"East Side Galleria"},
		"url":{"type":"Text","value":"https://www.visitberlin.de/en/east-side-gallery"},
		"telephone":{"type":"Text","value":"+49 30 1234 0003"},
		"countryCode":{"type":"Text","value":"DE"},
		"capacity":{"type":"Number","value":3650},
		"description":{"type":"Text","value":"Family-oriented supermarket with bakery and prepared food corner."},
		"image":{"type":"Text","value":"https://loremflickr.com/640/480/produce"}
  	},
  	{
  		"id":"urn:ngsi-ld:Store:004","type":"Store",
  		"address":{"type":"PostalAddress","value":{"streetAddress":"Panoramastraße 1A","addressRegion":"Berlin","addressLocality":"Mitte","postalCode":"10178"}},
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4094,52.5208]}},
		"name":{"type":"Text","value":"Tower Trodelmarkt"},
		"url":{"type":"Text","value":"https://www.visitberlin.de/en/alexanderplatz"},
		"telephone":{"type":"Text","value":"+49 30 1234 0004"},
		"countryCode":{"type":"Text","value":"DE"},
		"capacity":{"type":"Number","value":2900},
		"description":{"type":"Text","value":"Compact city-center store with fast checkout and essentials."},
		"image":{"type":"Text","value":"https://loremflickr.com/640/480/checkout"}
  	}
  ]
}'


#
# Create a series of Shelf Entities and place the in each Store.
# Each shelf is designed to hold one product.
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
	"actionType": "APPEND",
  "entities": [
	{
  		"id":"urn:ngsi-ld:Shelf:unit001","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3986112,52.554699]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit002","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3987221,52.554664]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 1"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit003","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3987221,52.554664]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 2"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit004","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.390311,52.507522]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit005","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.390309,52.50751]}},
  		"maxCapacity":{"type":"Integer","value":200},
  		"name":{"type":"Text","value":"Long Wall Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"}
  	},
  	{
  		"id":"urn:ngsi-ld:Shelf:unit006","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4447112,52.503199]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit007","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4447221,52.503164]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 1"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit008","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4447221,52.503164]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Wall Unit 2"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit009","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.444711,52.503122]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Corner Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit010","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.4094111,52.5208028]}},
  		"maxCapacity":{"type":"Integer","value":200},
  		"name":{"type":"Text","value":"Long Wall Unit"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:004"}
  	}
  ]
}'

#
# Create a series of Product Entities. 
# These are a series of alcoholc and non-alcoholic drinks which are available to sell.
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
    {
      "id":"urn:ngsi-ld:Product:001", "type":"Product",
      "name":{"type":"Text", "value":"Apples"},
      "size":{"type":"Text", "value": "S"},
			"price":{"type":"Integer", "value": 99},
			"color":{"type":"Text", "value":"#C62828"},
			"image":{"type":"Text", "value":"https://loremflickr.com/512/512/apple"}
    },
    {
      "id":"urn:ngsi-ld:Product:002", "type":"Product",
      "name":{"type":"Text", "value":"Bananas"},
      "size":{"type":"Text", "value": "M"},
			"price":{"type":"Integer", "value": 1099},
			"color":{"type":"Text", "value":"#F9A825"},
			"image":{"type":"Text", "value":"https://loremflickr.com/512/512/banana"}
    },
    {
      "id":"urn:ngsi-ld:Product:003", "type":"Product",
      "name":{"type":"Text", "value":"Coconuts"},
      "size":{"type":"Text", "value": "M"},
			"price":{"type":"Integer", "value": 1499},
			"color":{"type":"Text", "value":"#6D4C41"},
			"image":{"type":"Text", "value":"https://loremflickr.com/512/512/coconut"}
    },
    {
      "id":"urn:ngsi-ld:Product:004", "type":"Product",
      "name":{"type":"Text", "value":"Melons"},
      "size":{"type":"Text", "value": "XL"},
			"price":{"type":"Integer", "value": 5000},
			"color":{"type":"Text", "value":"#43A047"},
			"image":{"type":"Text", "value":"https://loremflickr.com/512/512/melon"}
    },
    {
      "id":"urn:ngsi-ld:Product:005", "type":"Product",
      "name":{"type":"Text", "value":"Kiwi Fruits"},
      "size":{"type":"Text", "value": "S"},
			"price":{"type":"Integer", "value": 99},
			"color":{"type":"Text", "value":"#7CB342"},
			"image":{"type":"Text", "value":"https://loremflickr.com/512/512/kiwi"}
    },
    {
      "id":"urn:ngsi-ld:Product:006", "type":"Product",
      "name":{"type":"Text", "value":"Strawberries"},
      "size":{"type":"Text", "value": "S"},
			"price":{"type":"Integer", "value": 99},
			"color":{"type":"Text", "value":"#D81B60"},
			"image":{"type":"Text", "value":"https://loremflickr.com/512/512/strawberry"}
    },
    {
      "id":"urn:ngsi-ld:Product:007", "type":"Product",
      "name":{"type":"Text", "value":"Raspberries"},
      "size":{"type":"Text", "value": "S"},
			"price":{"type":"Integer", "value": 99},
			"color":{"type":"Text", "value":"#AD1457"},
			"image":{"type":"Text", "value":"https://loremflickr.com/512/512/raspberry"}
    },
    {
      "id":"urn:ngsi-ld:Product:008", "type":"Product",
      "name":{"type":"Text", "value":"Pineapples"},
      "size":{"type":"Text", "value": "S"},
			"price":{"type":"Integer", "value": 99},
			"color":{"type":"Text", "value":"#FDD835"},
			"image":{"type":"Text", "value":"https://loremflickr.com/512/512/pineapple"}
    },
    {
      "id":"urn:ngsi-ld:Product:009", "type":"Product",
      "name":{"type":"Text", "value":"Oranges"},
      "size":{"type":"Text", "value": "S"},
			"price":{"type":"Integer", "value": 99},
			"color":{"type":"Text", "value":"#EF6C00"},
			"image":{"type":"Text", "value":"https://loremflickr.com/512/512/orange"}
    }
  ]
}'


#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:001
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:001","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit001"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":5}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:002","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit002"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:003"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:003","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit003"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:004"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	}
   
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:002
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:004","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit004"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:005","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit005"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:002"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	}
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:003
# Note that Shelf Unit009 is currently unused
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:006","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit006"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:007","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit007"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:008"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:008","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit008"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:009"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	}
   
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:004
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:401","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:004"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit010"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	}
   
  ]
}'

#
# Create four Employee Entities and assign one to each store.
#
curl -s -o /dev/null -X POST \
	'http://orion:1026/v2/op/update' \
	-H 'Content-Type: application/json' \
	-d '{
	"actionType":"APPEND",
	"entities":[
		{
			"id":"urn:ngsi-ld:Employee:001","type":"Employee",
			"name":{"type":"Text","value":"Lena Fischer"},
			"image":{"type":"Text","value":"https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg"},
			"salary":{"type":"Number","value":34000},
			"role":{"type":"Text","value":"manager"},
			"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"},
			"email":{"type":"Text","value":"lena.fischer@fiwaremarkets.local"},
			"dateOfContract":{"type":"Date","value":"2021-03-15"},
			"skills":{"type":"StructuredValue","value":["leadership","inventory planning","vendor negotiation"]},
			"username":{"type":"Text","value":"lfischer"},
			"password":{"type":"Text","value":"LenaPass2026"}
		},
		{
			"id":"urn:ngsi-ld:Employee:002","type":"Employee",
			"name":{"type":"Text","value":"Marco Weber"},
			"image":{"type":"Text","value":"https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg"},
			"salary":{"type":"Number","value":27000},
			"role":{"type":"Text","value":"cashier"},
			"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"},
			"email":{"type":"Text","value":"marco.weber@fiwaremarkets.local"},
			"dateOfContract":{"type":"Date","value":"2022-09-01"},
			"skills":{"type":"StructuredValue","value":["customer service","pos","cash balancing"]},
			"username":{"type":"Text","value":"mweber"},
			"password":{"type":"Text","value":"MarcoPass2026"}
		},
		{
			"id":"urn:ngsi-ld:Employee:003","type":"Employee",
			"name":{"type":"Text","value":"Sofia Kruger"},
			"image":{"type":"Text","value":"https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg"},
			"salary":{"type":"Number","value":29000},
			"role":{"type":"Text","value":"warehouse"},
			"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"},
			"email":{"type":"Text","value":"sofia.kruger@fiwaremarkets.local"},
			"dateOfContract":{"type":"Date","value":"2020-11-20"},
			"skills":{"type":"StructuredValue","value":["restocking","forklift","shelf optimization"]},
			"username":{"type":"Text","value":"skruger"},
			"password":{"type":"Text","value":"SofiaPass2026"}
		},
		{
			"id":"urn:ngsi-ld:Employee:004","type":"Employee",
			"name":{"type":"Text","value":"Jonas Neumann"},
			"image":{"type":"Text","value":"https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg"},
			"salary":{"type":"Number","value":25500},
			"role":{"type":"Text","value":"security"},
			"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:004"},
			"email":{"type":"Text","value":"jonas.neumann@fiwaremarkets.local"},
			"dateOfContract":{"type":"Date","value":"2023-05-08"},
			"skills":{"type":"StructuredValue","value":["incident response","loss prevention","safety checks"]},
			"username":{"type":"Text","value":"jneumann"},
			"password":{"type":"Text","value":"JonasPass2026"}
		}
	]
}'

echo -e " \033[1;32mdone\033[0m"
